### ISSUE TITLE
setup doesn't check dependencies (review of dependencies)

### ISSUE THREAD

**Issue by maweki** [kirienko/gourmet#108]
I don't know whether the `setup.py` should check dependencies. But I am currently trying to install `gourmet` in a basically empty docker (actually podman) container. It's a `toolbox` container that should allow you to install dev dependencies and stuff without cluttering your (possibly immutable) installation. I am doing all of this on fedora.

First it failed with:

```
running build_i18n
intltool-update -p -g gourmet
unable to execute 'intltool-update': No such file or directory
error: command 'intltool-update' failed with exit status 1
```

I fixed that with `sudo dnf install intltool`

Then I got many error messages `sh: file: command not found` which I fixed with `sudo dnf install file`. Then it worked. This might be a documentation issue but to get all the stuff built/installed from the `requirements.txt` I had to install all the following:

`sudo dnf install cairo-devel gcc python3-devel gobject-introspection-devel cairo-gobject-devel`

Then trying to run gourmet I get the following error:

```
Traceback (most recent call last):
  File "/home/maweki/.local/bin/gourmet", line 481, in <module>
    from gourmet import GourmetRecipeManager
  File "/home/maweki/.local/lib/python3.8/site-packages/gourmet/GourmetRecipeManager.py", line 12, in <module>
    from gi.repository import Gtk
  File "/home/maweki/.local/lib/python3.8/site-packages/gi/importer.py", line 132, in load_module
    raise ImportError('cannot import name %s, '
ImportError: cannot import name Gtk, introspection typelib not found
```
As it turns out, I still needed to install gtk3, which was a no-brainer `sudo dnf install gtk3`.

Then I got the following error:

```
Traceback (most recent call last):
  File "/home/maweki/.local/bin/gourmet", line 513, in <module>
    GourmetRecipeManager.startGUI()
  File "/home/maweki/.local/lib/python3.8/site-packages/gourmet/GourmetRecipeManager.py", line 707, in startGUI
    r=RecGui(splash_label=splash.label)
  File "/home/maweki/.local/lib/python3.8/site-packages/gourmet/GourmetRecipeManager.py", line 934, in __init__
    GourmetApplication.__init__(self, splash_label=splash_label)
  File "/home/maweki/.local/lib/python3.8/site-packages/gourmet/GourmetRecipeManager.py", line 84, in __init__
    self.setup_prefs() # Setup preferences...
  File "/home/maweki/.local/lib/python3.8/site-packages/gourmet/GourmetRecipeManager.py", line 102, in setup_prefs
    self.prefsGui = prefsGui.PreferencesGui(
  File "/home/maweki/.local/lib/python3.8/site-packages/gourmet/prefsGui.py", line 61, in __init__
    self.ui.add_from_file(uifile)
gi.repository.GLib.Error: g-file-error-quark: Failed to open file “/home/maweki/.local/share/ui/preferenceDialog.ui”: No such file or directory (4)
```

and this is actually #107 

This was just a review of all dependencies actually needed to build `gourmet` from source with all the dependencies. I have not checked what is actually documented and what isn't.

**Comment by cydanil** [comment]
Mostly fixed in #279 , the remaining are for package maintainers to ensure that system dependencies are referenced.
