### ISSUE TITLE
 Failed to open file “/usr/local/share/ui/preferenceDialog.ui”

### ISSUE THREAD

**Issue by dodona2** [kirienko/gourmet#129]
gi.repository.GLib.Error: g-file-error-quark: Failed to open file “/usr/local/share/ui/preferenceDialog.ui”: No such file or directory (4)

**Comment by cydanil** [comment]
Thanks for reporting this issue! :)

This issue arises when Gourmet is installed in place, and not in edit mode (ie. `pip install .` as opposed to `pip install -e .`).
We hadn't caught this issue, as in the CI, Gourmet is installed in edit mode.

It is due to the setup misusing relative paths (the files should be placed within the Gourmet installation folder). 
As far as I know @kirienko is looking into it.

Once the issue is resolved, we should consider doing some lightweight automated GUI testing with Dogtail on the build runner.

**Comment by dodona2** [comment]
python setup.py install fails wherever -e is places as well as pip install -e gourmet

**Comment by dodona2** [comment]
dnf install gourmet fails on fedora with:
No match for argument: gourmet
Error: Unable to find a match: gourmet
guess RH removed it (it was available in 31) because of the mentioned problem.

**Comment by dodona2** [comment]
after a git puöö 'python setup.py install' installs. However:
/usr/local/bin/gourmet 
-->
elib.intl failed to load.
IF YOU HAVE TROUBLE WITH TRANSLATIONS, MAKE SURE YOU HAVE THIS LIBRARY INSTALLED.
args = Namespace(db_url='', debug=None, debug_file='', gourmetdir='', html_plugin_dir='', thread_debug=False, thread_debug_interval=5.0, threads=False, time=False)
elib.intl failed to load.
IF YOU HAVE TROUBLE WITH TRANSLATIONS, MAKE SURE YOU HAVE THIS LIBRARY INSTALLED.
Traceback (most recent call last):
  File "/usr/local/bin/gourmet", line 481, in <module>
    from gourmet import GourmetRecipeManager
  File "/usr/local/lib/python3.8/site-packages/gourmet/GourmetRecipeManager.py", line 13, in <module>
    from . import batchEditor
  File "/usr/local/lib/python3.8/site-packages/gourmet/batchEditor.py", line 3, in <module>
    from . import gglobals
  File "/usr/local/lib/python3.8/site-packages/gourmet/gglobals.py", line 141, in <module>
    from .gtk_extras import dialog_extras
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 779, in exec_module
  File "<frozen importlib._bootstrap_external>", line 915, in get_code
  File "<frozen importlib._bootstrap_external>", line 972, in get_data
PermissionError: [Errno 13] Permission denied: '/usr/local/lib/python3.8/site-packages/gourmet/gtk_extras/dialog_extras.py'

**Comment by maweki** [comment]
>  guess RH removed it (it was available in 31) because of the mentioned problem.

no, it was removed because no python2 application is allowed in the standard repo
