### ISSUE TITLE
Space in image filenames crash the application.

### ISSUE THREAD

**Issue by cydanil** [kirienko/gourmet#189]
Selecting an image with spaces in its filename makes Gourmet crash hard, resulting in the following stack trace:
```python
Traceback (most recent call last):
  File "/home/cydanil/gourmet/gourmet/gtk_extras/dialog_extras.py", line 1126, in update_preview
    thumbpath = thumbnail.check_for_thumbnail(uri) #default size is large
  File "/home/cydanil/gourmet/gourmet/gtk_extras/thumbnail.py", line 41, in check_for_thumbnail
    return create_thumbnail(fn,name,uri,type)
  File "/home/cydanil/gourmet/gourmet/gtk_extras/thumbnail.py", line 62, in create_thumbnail
    mtime = os.stat(path)[8]
FileNotFoundError: [Errno 2] No such file or directory: '/home/cydanil/Documents/sour%20dough.jpg'
```

This is because of the `%20` (whitespace) escape.

**Comment by cydanil** [comment]
Cancelling an image also crashes, explicitly because it is not implemented correctly:
```python
Traceback (most recent call last):
  File "/home/cydanil/gourmet/gourmet/reccard.py", line 1553, in set_from_fileCB
    raise ValueError(f"Expected 1 filename, but got {qty}", qty)
ValueError: ('Expected 1 filename, but got 0', 0)
```

If no filename is provided, we should return early.

**Comment by cydanil** [comment]
`reccard.py` line 1540:

```python    
    def set_from_fileCB(self, widget: Gtk.Button):
        filenames = de.select_image("Select Image",
                                    action=Gtk.FileChooserAction.OPEN)
        if filenames is not None:
            fname, *_ = filenames
            Undo.UndoableObject(lambda *args: self.set_from_file(fname),
                                lambda *args: self.remove_image(),
                                self.rc.history,
                                widget=self.imageW).perform()
            self.edited = True
```

and `gtk_extra/thumbnail.py` line 60 should be something saner along the lines of:
```python
def create_thumbnail (path, thumbpath, uri, type="large"):
    """Create a thumbnail at path and return path"""
    path = path.replace('%20', ' ')
    mtime = os.stat(path)[8]
   [...]
```

**Comment by cydanil** [comment]
There's yet another place, at `gtk_extra.thumbnail.check_for_thumbnail`, where it fails:
```python
Traceback (most recent call last):
  File "/home/cydanil/gourmet/gourmet/gtk_extras/dialog_extras.py", line 1126, in update_preview
    thumbpath = thumbnail.check_for_thumbnail(uri)
  File "/home/cydanil/gourmet/gourmet/gtk_extras/thumbnail.py", line 51, in check_for_thumbnail
    fmtime = os.stat(fn)[8] # grab the modification time of this file
FileNotFoundError: [Errno 2] No such file or directory: '/home/cydanil/Documents/sour%20dough.jpg'
```

It seems that this `gtk_extra.thumbnail` first creates a thumbnail to drive, then loads it at a later time.
This ought to be done in memory.
