### ISSUE TITLE
gir-poppler 0.18 required in flatpak

### ISSUE THREAD

**Issue by cydanil** [kirienko/gourmet#222]
### Steps to Reproduce

1. When launching a flatpak, `gir-poppler` is not available resulting in the follow error:
```
  File "/app/lib/python3.8/site-packages/gi/__init__.py", line 126, in require_version                                                                                   
    raise ValueError('Namespace %s not available' % namespace)                                                                                                           
ValueError: Namespace Poppler not available                                                                                                                              
```
### Expected Behavior

Poppler should be available.

### Environment

* Operating System: Mint 2020
* Version or commit id: gourmet-011b10af.flatpak
* Installed as Flatpak or Python package?:

**Comment by cydanil** [comment]
Adding `poppler` to the manifest raises an error when trying load `pygobject` scanner:

```python
Traceback (most recent call last):
   File "/usr/bin/g-ir-scanner", line 103, in <module>
    from giscanner.scannermain import scanner_main
  File "/usr/lib/x86_64-linux-gnu/gobject-introspection/giscanner/scannermain.py", line 35, in <module>
    from giscanner.ast import Include, Namespace
  File "/usr/lib/x86_64-linux-gnu/gobject-introspection/giscanner/ast.py", line 29, in <module>
    from .sourcescanner import CTYPE_TYPEDEF, CSYMBOL_TYPE_TYPEDEF
  File "/usr/lib/x86_64-linux-gnu/gobject-introspection/giscanner/sourcescanner.py", line 35, in <module>
    from giscanner._giscanner import SourceScanner as CSourceScanner
ModuleNotFoundError: No module named 'giscanner._giscanner'
```

I think that disabling tools with `"-DENABLE_UTILS=OFF"` may help.

Here's a CI run: https://github.com/kirienko/gourmet/runs/1203832994?check_suite_focus=true

**Comment by cydanil** [comment]
I've sunk too much time attempting to fix this issue. I'm leaving it open, but I'm dropping the `alpha 2` milestone, as this is hindering further development.
