### ISSUE TITLE
Require Pillow 7.0.0 or greater

### ISSUE THREAD

**Issue by micahcochran** [kirienko/gourmet#318]
Pillow version 7.0.0 is required. `UnidentifiedImageError` was added in [Pillow 7.0.0](https://pillow.readthedocs.io/en/stable/releasenotes/7.0.0.html?highlight=UnidentifiedImageError#custom-unidentified-image-error).  

```Python
from PIL import Image, UnidentifiedImageError
```
That is an import line in image_utils.py as shown [here](https://github.com/kirienko/gourmet/blob/a0b5197cbfc18ff28d493c23f999eb59cebf44ea/src/gourmet/image_utils.py#L12).

All I had to do to fix this was upgrade it via `sudo pip3 install -U Pillow`.

### Steps to Reproduce
If you wanted to test this out. I guess you could force reinstall an older version of Pillow, such as `sudo pip3 install --force-reinstall Pillow==6.1.0`

### Expected Behavior
I would expect that pip's installation would either upgrade Pillow (preferable) or atleast give me an error message telling me that I need to upgrade Pillow.

### Current Behavior
Gourmet installed via pip without error.  (TL;DR It reports that I have pillow 6.1.0 installed.)
Here was the log of the installation:
```
⚡ 93% micah@micah-laptop:~/Downloads$ sudo pip3 install gourmet-c3ece056-py3-none-any.whl 
WARNING: The directory '/home/micah/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Processing ./gourmet-c3ece056-py3-none-any.whl
Requirement already satisfied: argcomplete in /usr/lib/python3/dist-packages (from gourmet==c3ece056) (1.8.1)
Requirement already satisfied: pygobject in /usr/lib/python3/dist-packages (from gourmet==c3ece056) (3.26.1)
Requirement already satisfied: beautifulsoup4 in /home/micah/.local/lib/python3.6/site-packages (from gourmet==c3ece056) (4.8.0)
Requirement already satisfied: requests in /home/micah/.local/lib/python3.6/site-packages (from gourmet==c3ece056) (2.22.0)
Requirement already satisfied: pillow in /home/micah/.local/lib/python3.6/site-packages (from gourmet==c3ece056) (6.1.0)
Requirement already satisfied: sqlalchemy in /usr/lib/python3/dist-packages (from gourmet==c3ece056) (1.1.11)
Requirement already satisfied: toml in /usr/lib/python3/dist-packages (from gourmet==c3ece056) (0.9.3)
Requirement already satisfied: soupsieve>=1.2 in /home/micah/.local/lib/python3.6/site-packages (from beautifulsoup4->gourmet==c3ece056) (1.9.4)
Requirement already satisfied: idna<2.9,>=2.5 in /home/micah/.local/lib/python3.6/site-packages (from requests->gourmet==c3ece056) (2.8)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /home/micah/.local/lib/python3.6/site-packages (from requests->gourmet==c3ece056) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in /home/micah/.local/lib/python3.6/site-packages (from requests->gourmet==c3ece056) (2019.9.11)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /home/micah/.local/lib/python3.6/site-packages (from requests->gourmet==c3ece056) (1.25.6)
Installing collected packages: gourmet
Successfully installed gourmet-1.0.0
WARNING: You are using pip version 20.2.3; however, version 20.2.4 is available.
You should consider upgrading via the '/usr/bin/python3 -m pip install --upgrade pip' command.
```

Here's what happen when I ran `gourmet`.
```
Traceback (most recent call last):
  File "/usr/local/bin/gourmet", line 5, in <module>
    from gourmet.GourmetRecipeManager import launch_app
  File "/usr/local/lib/python3.6/dist-packages/gourmet/GourmetRecipeManager.py", line 10, in <module>
    from gourmet import (batchEditor, convert, plugin, plugin_gui, plugin_loader,
  File "/usr/local/lib/python3.6/dist-packages/gourmet/batchEditor.py", line 5, in <module>
    from . import gglobals
  File "/usr/local/lib/python3.6/dist-packages/gourmet/gglobals.py", line 8, in <module>
    from .image_utils import load_pixbuf_from_resource
  File "/usr/local/lib/python3.6/dist-packages/gourmet/image_utils.py", line 12, in <module>
    from PIL import Image, UnidentifiedImageError
ImportError: cannot import name 'UnidentifiedImageError'
```

### Possible Solution
Require `pillow>=7.0.0` in setup.py.

### Environment
Pillow 6.1.0
Python 3.6.9 

* Operating System:
Ubuntu 18.04
* Version or commit id:
 v1.0.0-rc1 
* Installed as Flatpak or Python package?:
Installed via pip3.

**Comment by cydanil** [comment]
Thanks for reporting this problem! I overlooked it because my whole pc is pretty, uh, experimental :)

**Comment by micahcochran** [comment]
Thank you for fixing!
