### ISSUE TITLE
Recipes do not remove deleted ingredients from their listing

### ISSUE THREAD

**Issue by cydanil** [kirienko/gourmet#359]
### Steps to Reproduce

1. Select a recipe that has a deleted ingredient, and print it;  
2. Select `Print to File`, which should choose to create a PDF;  
3. Click Print.

This happens because an ingredient was deleted from the database, but not the recipe, which is equivalent to the following:

```sql
INSERT INTO "main"."ingredients" ("id", "recipe_id", "refid", "unit", "amount", "rangeamount", "item", "ingkey", "optional", "shopoptional", "inggroup", "position", "deleted") VALUES ('10', '2', '', '', '', '', '', '', '', '', '', '9', '0');
```

I would have attached the whole recipe, but the export is also broken by the nutritional plugin.

### Expected Behavior

The PDF should be created.  

### Current Behavior

The PDF creation fails and the following traceback occurs:  

```python
Error during Exporter
Traceback (most recent call last):
  File "/home/cydanil/gourmet/src/gourmet/threadManager.py", line 104, in run
    self.do_run()
  File "/home/cydanil/gourmet/src/gourmet/plugin_loader.py", line 440, in _
    retval = f(self,*args,**kwargs)
  File "/home/cydanil/gourmet/src/gourmet/exporters/exporter.py", line 582, in do_run
    e.do_run()
  File "/home/cydanil/gourmet/src/gourmet/exporters/exporter.py", line 88, in do_run
    self._write_text_()
  File "/home/cydanil/gourmet/src/gourmet/plugin_loader.py", line 441, in _
    retval = self.run_post_hook(f.__name__,retval,*args,**kwargs)
  File "/home/cydanil/gourmet/src/gourmet/plugin_loader.py", line 401, in run_post_hook
    retval = hook(retval,self,*args,**kwargs)
  File "/home/cydanil/gourmet/src/gourmet/plugin.py", line 200, in do_write
    val = field_fetcher(klass.r)
  File "/home/cydanil/gourmet/src/gourmet/plugins/nutritional_information/export_plugin.py", line 27, in get_nutritional_info_as_text_blob
    nutinfo = nd.get_nutinfo_for_inglist(rd.get_ings(rec),rd)
  File "/home/cydanil/gourmet/src/gourmet/plugins/nutritional_information/nutrition.py", line 124, in get_nutinfo_for_inglist
    return NutritionInfoList([self.get_nutinfo_for_ing(i,rd, multiplier) for i in inglist],
  File "/home/cydanil/gourmet/src/gourmet/plugins/nutritional_information/nutrition.py", line 124, in <listcomp>
    return NutritionInfoList([self.get_nutinfo_for_ing(i,rd, multiplier) for i in inglist],
  File "/home/cydanil/gourmet/src/gourmet/plugins/nutritional_information/nutrition.py", line 118, in get_nutinfo_for_ing
    return  self.get_nutinfo_for_item(ing.ingkey,amount,ing.unit,ingObject=ing)
  File "/home/cydanil/gourmet/src/gourmet/plugins/nutritional_information/nutrition.py", line 130, in get_nutinfo_for_item
    ni=self.get_nutinfo(key)
  File "/home/cydanil/gourmet/src/gourmet/plugins/nutritional_information/nutrition.py", line 166, in get_nutinfo
    ni = self.get_nutinfo_from_desc(key)
  File "/home/cydanil/gourmet/src/gourmet/plugins/nutritional_information/nutrition.py", line 148, in get_nutinfo_from_desc
    matches = self.get_matches(desc)
  File "/home/cydanil/gourmet/src/gourmet/plugins/nutritional_information/nutrition.py", line 83, in get_matches
    words=re.split(r"\W",key)
  File "/home/cydanil/miniconda3/lib/python3.7/re.py", line 213, in split
    return _compile(pattern, flags).split(string, maxsplit)
TypeError: expected string or bytes-like object

Traceback (most recent call last):
  File "/home/cydanil/gourmet/src/gourmet/plugins/import_export/pdf_plugin/print_plugin.py", line 202, in handle_error
    raise Exception('There was an error generating a PDF to print')
Exception: There was an error generating a PDF to print
```
### Environment

* Operating System: Elementary OS
* Version or commit id: `1.0.0`
* Installed as Flatpak or Python package?: source

**Comment by cydanil** [comment]
I cannot reproduce this behaviour.
